function genQuote() {
    var randNum = Math.floor(Math.random() * 84) + 1;
    document.getElementById("quote").innerHTML = quotes[randNum];
  }
  
  //listado de frases
  var quotes = [
    "he escrito a mi ex una noche de fiesta",
    "he fingido estar en un videoclip cuando salgo de la ducha mientras pongo caras intensas en el espejo",
    "he hecho un spoiler de Juego de Tronos",
    "he hecho pis en una piscina con miedo por si aparecía el circulo rojo",
    "he fingido que me llamaban para escapar de una cita",
    "he estado más de tres días sin ducharme",
    "me he apuntado al gimnasio pero no he ido jamás",
    "he stalkeado el instagram del el/la ex de mi novi@",
    "me he dado el pisto en una entrevista de trabajo",
    "he cantado en el Singstar “Cuando zarpa el amor” de Camela",
    "he apuntado con la linterna mi boca para enseñarle las placas a un amigo",
    "he abierto a la policía por haber hecho un fiestón en casa",
    "me he imaginado siendo del sexo opuesto",
    "he llamado mamá a mi profesora",
    "me he pasado mi parada del bus volviendo de fiesta y he acabao en otra parte",
    "he  perdido un movil",
    "he llevado unas gafas de cristal solo por posturear",
    "me autoavergüenzo de haber sido fan de Crepúsculo",
    "he pesado la fruta, le he pegado el ticket y luego he metido más",
    "mentí en el Yo Nunca",
    "he estornudado y me ha salido un moco",
    "he preguntado a alguien que no trabajaba en una tienda si tenía mi talla",
    "he confundido a una persona con un camarero en un restaurante",
    "he indicado mal un camino cuando me han preguntado",
    "he olido mi propio pedo",
    "he movido la boca aunque no me sepa la canción",
    "he fingido un desmayo para darle dramatismo a una situación",
    "he intentado mover cosas con la mente (sin resultado)",
    "he flirteado con el novio de un amig@",
    "he cotilleado a quién daba like mis exparejas",
    "he mirado el papel después de ir al baño",
    "he acosado por redes sociales a mi artista favorito",
    "me he creído Mr Robot al instalar un programa pirata",
    "he mandado un audio subidito de tono a mi madre por error",
    "El/La jugador de mi derecha bebe 2 tragos", 
    "he perreado con BadBunny",
    "El/La mas mayor del grupo bebe 3 tragos",
    "El/La  menor del grupo bebe 3 tragos",
    "El/La mas mayor del grupo mandar beber 6 tragos(repartidos)",
    "El/La  menor del grupo mandar beber 6 tragos(repartidos)",
    "A votacion popular se eligen 2 jugadores y se tendran que pasar un chupito entre ellos",
    "A votacion popular se eligen 2 jugadores y uno de ellos tendra que beber un chupito del omgligo del otro",
    "he tenido sexo en este lugar",
    "Los jugadores/as elegiran quien tiene que hacer 3 burpees, si se niega debera beber 5 tragos",
    "he cantado Tusa gritando",
    "El/La jugador mas bailonga tiene que bailar teerk durante 5 segundas, si no bebe 4 tragos",
    "El/La jugador mas moreno de piel bebe 2 tragos",
    "El/La jugador mas blanco de piel bebe 2 tragos",
    "Los/Las rubios beben 3 tragos",
    "Los/Las rubios reparten 3 tragos",
    "Los/Las morenos/as beben 3 tragos",
    "Los/Las morenos/asreparten 3 tragos",
    "Los/Las miopes beben 3 tragos",
    "Los/Las miopes reparten 5 tragos",
    "he tenido sexo en un sitio público",
    "Quien es mas probable que pruebe el sado, la persona mas señalada tendra que beber tantos tragos como votos obtenidos",
    "Quien creeis que hace el mejor sexo oral,la persona mas señalada tendra que beber tantos tragos como votos obtenidos",
    "he escuchado a mis padres tener sexo",
    "Quien es mas probable que se lie con mas de una persona en una noche, la persona mas señalada tendra que beber tantos tragos como votos obtenidos",
    "El/La jugador mas mayor bebe tantos tragos como euros tenga en la cartera",
    "El/La jugador mas pequeño bebe tantos tragos como euros tenga en la cartera",
    "Los/Las jugadores que llever al menor un preservativo en la cartera beben 2 tragos",
    "Los/Las jugadores pelirrojos beben 4 tragos",
    "Si te han bloqueado de Instagram bebe 2 tragos",
    "he vomitado en este lugar",
    "he pensado que quien tiene el movil es sexy",
    "me he masturbado mas de 3 veces en un dia",
    "he follado mas de 3 veces o mas en un dia",
    "Quien es mas probable que rompa algo esta noche,la persona mas señalada tendra que beber tantos tragos como votos obtenidos",
    "La persona mas bajita bebe 2 tragos (para que pegue el estirón)",
    "Quien es mas probable que haga el ridiculo en publico, la persona mas señalada tendra que beber tantos tragos como votos obtenidos",
    "Acepta el reto, si puedes decir 3 veces 'no te rayes Yerry' en 5 segundos manda 6 tragos, si no bebe 2 tragos",
    "he vuelto con mi ex",
    "me he liado con el/la ex de un amigo",
    " me he follado con el/la ex de un amigo",
    "me he tirado un pedo y he dicho que mal huele para despistar",
    "he dicho que me gusta un regalo y luego lo he devuelto",
    "he escrito a mi ex en una noche de fiesta",
    "he hecho pis en una piscina por miedo a que saliera el liquido azul",
    "nunca he estado mas de 3 dias sin ducharme",
    "he movido la boca aunque no me sepa la cancion",
    "El/La jugador mas alto bebe 3 tragos",
    "El/La jugador mas gordito/a hace 5 flexiones, si no bebe 5 tragos",
    "Los/Las jugadores que solo fumen de fiesta beben 2 tragos",
    "he probado drogas duras"
  ];
  